# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://stoneworldimpex.com
title: Stone World ImpEx
email: janet_stoneworld@yahoo.com
description: > # "Realizing the potential of Philippine made furniture int the world market, 1988 saw the humble beginnings of the company name Stoneworld Impex, which started with the production of fossil stone and later on expanded and ventured into other production line such as casted stone, fiber cast wrought iron, leather inlay, rattan can and other indigenous materials. Today, the company operation encompasses 6 productions plats with total land area of about 30,000 square meters whose designs & quality are highly acclaimed worldwide."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/stoneworldimpex
